@startuml
skinparam monochrome true
skinparam backgroundColor white
skinparam defaultFontColor black
skinparam ConditionEndStyle hline
skinparam ArrowColor black

start

:Ініціалізація стекової машини;
note right
  Налаштування регістрів
  та стека операндів
end note

while (Є елементи RPN для обробки?) is (Так)
  :Отримати поточну лексему RPN;
  
  if (Лексема є операндом?) then (Так)
    :Згенерувати код\nдля завантаження операнда на стек;
    
  elseif (Унарний оператор?) then (Так)
    :Згенерувати код\nдля унарної операції;
    
  elseif (Бінарний оператор?) then (Так)
    :Згенерувати код\nдля бінарної операції;
    
  elseif (Оператор присвоєння?) then (Так)
    :Згенерувати код\nдля запису в пам'ять;
    
  elseif (Оператор введення/виведення?) then (Так)
    :Згенерувати код\nдля виклику процедури I/O;
    
  elseif (Мітка?) then (Так)
    :Зберегти адресу мітки\nв таблиці міток;
    
  elseif (Оператор переходу?) then (Так)
    :Згенерувати код переходу;
    :Зберегти позицію для патчингу;
    
  endif
  
endwhile (Ні)

:Патчинг адрес переходів;
note right
  Заповнення адрес міток
  у командах переходу
end note

:Зберегти згенерований код у файл .asm;

stop

@enduml
